# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-28 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160827_1412'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Notes',
        ),
        migrations.AlterModelTable(
            name='notes',
            table=None,
        ),
    ]
