# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 19:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170220_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='name',
            new_name='subject_name',
        ),
        migrations.AddField(
            model_name='notes',
            name='branch',
            field=models.CharField(default=10, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='year',
            field=models.IntegerField(default=2017),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notes',
            name='picture',
            field=models.ImageField(upload_to=b'blog/media/year/brach/subject_name/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 22, 19, 0, 49, 796384, tzinfo=utc)),
        ),
    ]
