# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 19:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170222_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=55)),
                ('year', models.IntegerField()),
                ('subject_name', models.CharField(max_length=15)),
                ('picture', models.ImageField(upload_to=b'blog/media/year/brach/subject_name/')),
            ],
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 22, 19, 10, 47, 973582, tzinfo=utc)),
        ),
    ]
