# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170222_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='unit',
            field=models.IntegerField(choices=[(1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5'), (6, b'6'), (7, b'7'), (8, b'8'), (9, b'9'), (10, b'10')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='branch',
            field=models.CharField(choices=[(b'IT', b'IT'), (b'EE', b'EE'), (b'CSE', b'CSE'), (b'EC', b'EC'), (b'ME', b'ME'), (b'CE', b'CE')], max_length=55),
        ),
        migrations.AlterField(
            model_name='note',
            name='picture',
            field=models.ImageField(upload_to=b'blog/media/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='year',
            field=models.IntegerField(choices=[(1, b'First'), (2, b'Second'), (3, b'Third'), (4, b'Fourth')]),
        ),
    ]
