# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-23 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170222_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='picture',
            field=models.ImageField(upload_to=b'media/images'),
        ),
    ]
