# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-24 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170223_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='picture',
            field=models.ImageField(upload_to=b'images'),
        ),
    ]
