# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-25 05:19
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170224_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='picture',
            field=models.ImageField(upload_to='images'),
        ),
    ]
