# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-25 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170225_0519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
