# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-27 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20170227_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publish_date',
        ),
    ]
