# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-27 07:09
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_post_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field=b'height_field', null=True, upload_to=blog.models.generate_post_name, width_field=b'width_field'),
        ),
    ]
