# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import notes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.IntegerField()),
                ('picture', models.ImageField(upload_to=notes.models.generate_picture_name)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('no_of_units', models.IntegerField()),
                ('year', models.IntegerField(choices=[(1, b'First'), (2, b'Second'), (3, b'Third'), (4, b'Fourth')])),
                ('branch', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Subject'),
        ),
    ]
