# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-25 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[(b'IT', b'IT'), (b'EE', b'EE'), (b'CSE', b'CSE'), (b'EC', b'EC'), (b'ME', b'ME'), (b'CE', b'CE')], max_length=55)),
                ('year', models.IntegerField(choices=[(1, b'First'), (2, b'Second'), (3, b'Third'), (4, b'Fourth')])),
                ('subject_name', models.CharField(max_length=15)),
                ('unit', models.IntegerField(choices=[(1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5'), (6, b'6'), (7, b'7'), (8, b'8'), (9, b'9'), (10, b'10')])),
                ('picture', models.ImageField(upload_to=b'images')),
            ],
        ),
    ]
