# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='branch',
            field=models.CharField(choices=[(b'IT', b'IT'), (b'EE', b'EE'), (b'CSE', b'CSE'), (b'EC', b'EC'), (b'ME', b'ME'), (b'CE', b'CE')], max_length=15),
        ),
    ]
