# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-25 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import notes.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='picture',
            field=models.ImageField(upload_to=notes.models.generate_picture_name),
        ),
    ]
