# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20170225_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1, b'First'), (2, b'Second'), (3, b'Third'), (4, b'Fourth')])),
                ('branch', models.CharField(max_length=100)),
                ('subjects', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='subject_name',
            field=models.CharField(choices=[(b'DS', b'Data Structure'), (b'OS', b'Operating sytem'), (b'EC', b'Ecomomics'), (b'Thermo', b'Thermo')], max_length=10),
        ),
    ]
