# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20170311_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='unit_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
