# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_remove_note_unit_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='unit',
        ),
    ]
