# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_note_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='unit_no',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
